### ISSUE TITLE
conda.md: source need to be changed to conda

### ISSUE THREAD

**Issue by dnastars** [fcbg-hnp/best-practice#1]
In the  last example, at line 3:
source has to be changed to conda

**Comment by mick-d** [comment]
Well spotted! Could you please made a pull request :) ?

If you save your commands, this will be a good example to show at the meeting showing github PR.

**Comment by mick-d** [comment]
Thanks for solving it with commit 57eb9d44caaacc89a050d5c7b2ef9f370a1ca33a
